[versions]
analytics = "3.0.0"
assertj = "3.26.3"
changelog = "2.2.1"
checkstyle = "10.15.0"
commons-text = "1.12.0"
flexmark = "0.64.8"
gradle-intellij-plugin-version = "1.17.3"
gson = "2.10.1"
jackson = "2.17.2"
jsoup = "1.17.2"
jtokkit = "1.1.0"
junit = "5.11.0"
kotlin = "2.0.0"
llm-client = "0.8.12"
okio = "3.9.0"
tree-sitter = "0.22.6a"

[libraries]
analytics = { module = "com.rudderstack.sdk.java.analytics:analytics", version.ref = "analytics" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj" }
commons-text = { module = "org.apache.commons:commons-text", version.ref = "commons-text" }
flexmark-all = { module = "com.vladsch.flexmark:flexmark-all", version.ref = "flexmark" }
gradle-intellij-plugin = { module = "org.jetbrains.intellij.plugins:gradle-intellij-plugin", version.ref = "gradle-intellij-plugin-version" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
jtokkit = { module = "com.knuddels:jtokkit", version.ref = "jtokkit" }
junit-bom = { module = "org.junit:junit-bom", version.ref = "junit" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
llm-client = { module = "ee.carlrobert:llm-client", version.ref = "llm-client" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
tree-sitter = { module = "io.github.bonede:tree-sitter", version.ref = "tree-sitter" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
